Jmol_backbone = [
    '# Jmol state version 14.6.4_2016.11.05  2016-11-10 03:30;\n',
    '\n',
    'function _setWindowState() {\n',
    '# width 1844;\n',
    '# height 956;\n',
    '  stateVersion = 1406004;\n',
    '  background [x000000];\n',
    '  axis1Color = "[xff0000]";\n',
    '  axis2Color = "[x008000]";\n',
    '  axis3Color = "[x0000ff]";\n',
    '  set ambientPercent 45;\n',
    '  set diffusePercent 84;\n',
    '  set specular true;\n',
    '  set specularPercent 22;\n',
    '  set specularPower 40;\n',
    '  set specularExponent 6;\n',
    '  set celShading false;\n',
    '  set celShadingPower 10;\n',
    '  set zShadePower 3;\n',
    '}\n',
    '\n',
    'function _setFileState() {\n',
    '\n',
    '  set allowEmbeddedScripts false;\n',
    '  set appendNew true;\n',
    '  set appletProxy "";\n',
    '  set applySymmetryToBonds false;\n',
    '  set autoBond true;\n',
    '  set bondRadiusMilliAngstroms 150;\n',
    '  set bondTolerance 0.45;\n',
    '  set defaultLattice {0.0 0.0 0.0};\n',
    '  set defaultLoadFilter "";\n',
    '  set defaultLoadScript "";\n',
    '  set defaultStructureDssp true;\n',
    '  set defaultVDW Auto;\n',
    '  set forceAutoBond false;\n',
    '  #set defaultDirectory "/home/kate";\n',
    '  #set loadFormat "https://files.rcsb.org/download/%FILE.pdb";\n',
    '  #set loadLigandFormat "https://files.rcsb.org/ligands/download/%FILE.cif";\n',
    '  #set smilesUrlFormat "https://cactus.nci.nih.gov/chemical/structure/%FILE/file?format=sdf&get3d=true";\n',
    '  #set nihResolverFormat "https://cactus.nci.nih.gov/chemical/structure/%FILE";\n',
    '  #set pubChemFormat "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/%FILE/SDF?record_type=3d";\n',
    '  #set edsUrlFormat "http://eds.bmc.uu.se/eds/dfs/%c2%c3/%file/%file.omap";\n',
    '  #set edsUrlFormatDiff "http://eds.bmc.uu.se/eds/dfs/%c2%c3/%file/%file_diff.omap";\n',
    '  #set edsUrlCutoff "http://eds.bmc.uu.se/eds/dfs/%c2%c3/%file/%file.sfdat";\n',
    '  set bondingVersion 0;\n',
    '  set legacyAutoBonding false;\n',
    '  set legacyHAddition false;\n',
    '  set legacyJavaFloat false;\n',
    '  set minBondDistance 0.4;\n',
    '  set minimizationCriterion  0.001;\n',
    '  set minimizationSteps  100;\n',
    '  set multipleBondBananas false;\n',
    '  set pdbAddHydrogens false;\n',
    '  set pdbGetHeader false;\n',
    '  set pdbSequential false;\n',
    '  set percentVdwAtom 23;\n',
    '  set smallMoleculeMaxAtoms 40000;\n',
    '  set smartAromatic true;\n',
    '  load /*file*/"./PDB_COMPLEX";\n',
    '\n',
    '}\n',
    '\n',
    'function _setParameterState() {\n',
    '\n',
    '   set defaultanglelabel "%VALUE %UNITS";\n',
    '   set defaultcolorscheme "jmol";\n',
    '   set defaultdistancelabel "%VALUE %UNITS";\n',
    '   set defaultdrawarrowscale 0.5;\n',
    '   set defaultlabelpdb "%m%r";\n',
    '   set defaultlabelxyz "%a";\n',
    '   set defaultlattice "{0 0 0}";\n',
    '   set defaultloadfilter "";\n',
    '   set defaultloadscript "";\n',
    '   set defaulttorsionlabel "%VALUE %UNITS";\n',
    '   set defaulttranslucent 0.5;\n',
    '   set defaultvdw "Auto";\n',
    '  set allowembeddedscripts true;\n',
    '  set allowmoveatoms false;\n',
    '  set allowrotateselected false;\n',
    '  set animationmode "once";\n',
    '  set appletproxy "";\n',
    '  set applysymmetrytobonds false;\n',
    '  set atomtypes "";\n',
    '  set autobond true;\n',
    '  set autofps false;\n',
    '  set axes window;\n',
    '  set axesmode 0;\n',
    '  set axesoffset 0.0;\n',
    '  set axesscale 2.0;\n',
    '  set backbonesteps false;\n',
    '  set bondmodeor false;\n',
    '  set bondradiusmilliangstroms 150;\n',
    '  set bondtolerance 0.45;\n',
    '  set cartoonbaseedges false;\n',
    '  set cartoonfancy false;\n',
    '  set cartoonladders false;\n',
    '  set cartoonrockets false;\n',
    '  set chaincasesensitive false;\n',
    '  set dataseparator "~~~";\n',
    '  set defaultstructuredssp true;\n',
    '  set delaymaximumms 0;\n',
    '  set dipolescale 1.0;\n',
    '  set disablepopupmenu false;\n',
    '  set displaycellparameters true;\n',
    '  set dotdensity 3;\n',
    '  set dotscale 1;\n',
    '  set dotsselectedonly false;\n',
    '  set dotsurface true;\n',
    '  set dragselected false;\n',
    '  set drawfontsize 14.0;\n',
    '  set drawhover false;\n',
    '  set dsspcalculatehydrogenalways true;\n',
    '  set edsurlformatdiff "http://eds.bmc.uu.se/eds/dfs/%c2%c3/%file/%file_diff.omap";\n',
    '  set ellipsoidarcs false;\n',
    '  set ellipsoidarrows false;\n',
    '  set ellipsoidaxes false;\n',
    '  set ellipsoidaxisdiameter 0.02;\n',
    '  set ellipsoidball true;\n',
    '  set ellipsoiddotcount 200;\n',
    '  set ellipsoiddots false;\n',
    '  set ellipsoidfill false;\n',
    '  set energyunits "kJ";\n',
    '  set forceautobond false;\n',
    '  set gestureswipefactor 1.0;\n',
    '  set greyscalerendering false;\n',
    '  set hbondsangleminimum 90.0;\n',
    '  set hbondsbackbone false;\n',
    '  set hbondsdistancemaximum 3.25;\n',
    '  set hbondsrasmol true;\n',
    '  set hbondssolid false;\n',
    '  set helixstep 1;\n',
    '  set helppath "http://chemapps.stolaf.edu/jmol/docs/index.htm";\n',
    '  set hermitelevel 0;\n',
    '  set hiddenlinesdashed false;\n',
    '  set hidenameinpopup false;\n',
    '  set hidenavigationpoint false;\n',
    '  set highresolution false;\n',
    '  set hoverdelay 0.5;\n',
    '  set isosurfacekey false;\n',
    '  set isosurfacepropertysmoothing true;\n',
    '  set isosurfacepropertysmoothingpower 7;\n',
    '  set justifymeasurements false;\n',
    '  set loadatomdatatolerance 0.01;\n',
    '  set measureallmodels false;\n',
    '  set measurementlabels true;\n',
    '  set meshscale 1;\n',
    '  set messagestylechime false;\n',
    '  set minbonddistance 0.4;\n',
    '  set minimizationcriterion 0.001;\n',
    '  set minimizationrefresh true;\n',
    '  set minimizationsilent false;\n',
    '  set minimizationsteps 100;\n',
    '  set minpixelselradius 6;\n',
    '  set modulationscale 1.0;\n',
    '  set monitorenergy false;\n',
    '  set multiplebondbananas false;\n',
    '  set multiplebondradiusfactor 0.0;\n',
    '  set multiplebondspacing -1.0;\n',
    '  set navigationperiodic false;\n',
    '  set navigationspeed 5.0;\n',
    '  set nmrpredictformat "http://www.nmrdb.org/service/predictor?POST?molfile=";\n',
    '  set nmrurlformat "http://www.nmrdb.org/new_predictor?POST?molfile=";\n',
    '  set partialdots false;\n',
    '  set particleradius 20.0;\n',
    '  set pdbaddhydrogens false;\n',
    '  set pdbgetheader false;\n',
    '  set pdbsequential false;\n',
    '  set percentvdwatom 23;\n',
    '  set pickingspinrate 10;\n',
    '  set pointgroupdistancetolerance 0.2;\n',
    '  set pointgrouplineartolerance 8.0;\n',
    '  set propertyatomnumbercolumncount 0;\n',
    '  set propertyatomnumberfield 0;\n',
    '  set propertycolorscheme "roygb";\n',
    '  set propertydatacolumncount 0;\n',
    '  set propertydatafield 0;\n',
    '  set quaternionframe "p";\n',
    '  set rangeselected false;\n',
    '  set ribbonaspectratio 16;\n',
    '  set ribbonborder false;\n',
    '  set rocketbarrels false;\n',
    '  set selecthetero true;\n',
    '  set selecthydrogen true;\n',
    '  set sheetsmoothing 1.0;\n',
    '  set showhiddenselectionhalos false;\n',
    '  set showhydrogens true;\n',
    '  set showmeasurements true;\n',
    '  set showmodulationvectors false;\n',
    '  set showmultiplebonds true;\n',
    '  set shownavigationpointalways false;\n',
    '  set showunitcelldetails true;\n',
    '  set slabbyatom false;\n',
    '  set slabbymolecule false;\n',
    '  set smallmoleculemaxatoms 40000;\n',
    '  set smartaromatic true;\n',
    '  set solventprobe false;\n',
    '  set solventproberadius 1.2;\n',
    '  set ssbondsbackbone false;\n',
    '  set starwidth 0.05;\n',
    '  set stereodegrees -5;\n',
    '  set strandcountformeshribbon 7;\n',
    '  set strandcountforstrands 5;\n',
    '  set strutdefaultradius 0.3;\n',
    '  set strutlengthmaximum 7.0;\n',
    '  set strutsmultiple false;\n',
    '  set strutspacing 6;\n',
    '  set tracealpha true;\n',
    '  set translucent true;\n',
    '  set twistedsheets false;\n',
    '  set usenumberlocalization true;\n',
    '  set vectorscale 1.0;\n',
    '  set vectorscentered false;\n',
    '  set vectorsymmetry false;\n',
    '  set vectortrail 0;\n',
    '  set vibrationscale 0.5;\n',
    '  set waitformoveto true;\n',
    '  set wireframerotation false;\n',
    '  set zdepth 0;\n',
    '  set zoomheight false;\n',
    '  set zoomlarge true;\n',
    '  set zslab 50;\n',
    '\n',
    '}\n',
    '\n',
    'function _setModelState() {\n',
    '\n',
    '  select ({GUEST_LIST});\n',
    '  color atoms opaque [x00ffff];\n',
    '  select ({HOST_LIST});\n',
    '  color atoms opaque [x008000];\n',
    '  measures delete;\n',
    '  measure ({GUEST_DIS}) ({HOST_DIS});\n',
    '\n',
    '  select *; set measures nanometers;\n',
    '  font measures 15.0 SansSerif Plain;\n',
    '  select measures ({0:6});\n',
    '  measure "2:%VALUE %UNITS//nanometers";\n',
    '  select measures ({null});\n',
    '\n',
    '  hover "%U";\n',
    '\n',
    '  frank on;\n',
    '  font frank 16.0 SansSerif Plain;\n',
    '  select *;\n',
    '  set fontScaling false;\n',
    '\n',
    '}\n',
    '\n',
    'function _setState() {\n',
    '  initialize;\n',
    '  set refreshing false;\n',
    '  _setWindowState;\n',
    '  _setFileState;\n',
    '  _setParameterState;\n',
    '  _setModelState;\n',
    '  _setPerspectiveState;\n',
    '  _setSelectionState;\n',
    '  set refreshing true;\n',
    '  set antialiasDisplay false;\n',
    '  set antialiasTranslucent true;\n',
    '  set antialiasImages true;\n',
    '}\n',
    '\n',
    '_setState;\n'
]
